name = "Tango"
uuid = "0d1e0b74-c5ac-45fa-bedc-119f8e303512"
authors = ["tobyvg <tobyvangastelen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
